spring.application.name=CommerceFinder-API

# Configurações de Conexão do H2
spring.datasource.url=jdbc:h2:mem:commercefinder_db
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=org.h2.Driver

# Configurações do Hibernate / JPA para H2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativar o Console Web do H2 para visualizar o banco
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Muda o caminho padrão do Swagger para algo mais simples (opcional)
springdoc.swagger-ui.path=/swagger

# Ordena os endpoints por método HTTP (GET, POST, PUT, DELETE) na tela
springdoc.swagger-ui.operationsSorter=alpha